### PR TITLE
Get Lint working on 0.6

### LINKED ISSUE #79: Incorrect type assumption with int()
```
function lmatrix(g::Graph)
    n_v = nv(g)
    A = int(adjacency_matrix(g))   # note that this creates a sparse matrix of integers
    D = spdiagm(sum(A,2)[:])
    return D - A
end
```

yields

```
ERROR  sum: ErrorException("no method found for the specified argument types")
                                         Signature: (Int64,Int64)
```

Also curiously, it doesn't warn that I'm not using `n_v`.

### LINKED ISSUE #137: False positive when constructor possibly raises error
``` julia
julia> lintstr("""
       immutable Test
           Test(x) = x ? new() : error("constructor must be true")
       end
       """)
1-element Array{Lint.LintMessage,1}:
 none:2 E611 : constructor doesn't seem to return the constructed object
```

this is a common idiom for checking invariants

### PR DESCRIPTION
**Pull request by TotalVerb**
The first commit converts DataType to Type everywhere. This should always have been the case, but is especially important in 0.6, as many types like `Array` are now `UnionAll`s instead of `DataType`s.

The second commit rewrites the version constraint code to not call `eval`. Not calling `eval` is a good idea anyway, but is especially important in 0.6 due to the world age restrictions. The calling of new methods created with `eval` is subject to world age restrictions in 0.6, and removing the `eval` addresses that issue.

The third commit changes from `typeof(x) == T` to `isa(x, T)` in many places. 0.6 introduces new `x isa T` syntax which would make sense to use in the future, and this is a first step toward that modernization.

The fourth commit addresses the remaining, miscellaneous problems that prevent Lint from working properly on 0.6, and involves some updates to legacy code (this fixes several issues along the way). Overall, Lint should be better at detecting types. Once 0.4 support is dropped, large amounts of code can be removed.

The fifth commit (in progress) fixes breakage of 0.4 and 0.5 introduced by the first four commits.

Fixes #79 
Fixes #137

### CODE REVIEW

**Comment by TotalVerb** [comment]
There was some code incorrectly supposing that `slicedim` always returns either a vector or a matrix, when in fact this depends on the values of the arguments. Removing that code is necessary for the tests to pass on 0.6, where inference is used to guess the result type instead.

**Comment by TotalVerb** [comment]
All the tests are passing and I think this is ready to go after review!

@tonyhffong 
@Michael-Klassen 

Once this is in I'll have another PR fixing up minor issues and cleaning up some loose ends.

File: test/typecheck.jl [hunk 1]
```diff
@@ -148,7 +148,7 @@ end
 msgs = lintstr(s)
 @test msgs[1].code == :E521
 @test msgs[1].variable == "a"
-@test contains(msgs[1].message, "apparent type DataType is not a container type")
+@test contains(msgs[1].message, "apparent type Type")
```
Comment (Michael-Klassen) [inline test/typecheck.jl]: Keep the wording on this error message or change it to be more descriptive.

Comment (TotalVerb) [inline test/typecheck.jl]: The error message is actually the same. I had to change the test because it prints as `Type{T}` on 0.5 or `Type` on 0.6, and I didn't want to select which based off version.

Comment (TotalVerb) [inline test/typecheck.jl]: I think, going forward, we will want to standardize the error messages based off error codes, and then disassociate the testing of linting creating the right error code, and testing the error codes being associated with an appropriately descriptive message.
