### PR TITLE
Miscellaneous cleanup

### LINKED ISSUE #136: `lintpkg` broken
Doesn't actually print anything. Only returns stuff when keyword argument is set.

### PR DESCRIPTION
**Pull request by TotalVerb**
First commit should be relatively uncontroversial. `String` means something different on 0.5, so this error should be turned off.

Second commit removes message I581, which was never correct. `Dict(:a => 1, :b => 2)` is already a `Dict{Symbol, Int}` and adding in the type annotations is not necessary for better performance.

Third commit replaces `returnMsgs` keyword argument with a `LintResult` type that is always returned, but displays well in multi-line. It retains all the `AbstractVector{LintMessage}` functionality by extending it. While I think this is a good idea, it would be good to get other opinions. (This also fixes #136.)

### CODE REVIEW

**Comment by Michael-Klassen** [comment]
I get this error when trying to run your branch.
```julia
julia> lintpkg("Lint")
Error showing value of type Lint.LintResult:
ERROR: MethodError: `size` has no method matching size(::Lint.LintResult)
Closest candidates are:
  size{T,n}(::AbstractArray{T,n}, ::Any)
  size(::Any, ::Integer, ::Integer, ::Integer...)
 in writemime at replutil.jl:20
 in display at REPL.jl:114
 in display at REPL.jl:117
 [inlined code] from multimedia.jl:151
 in display at multimedia.jl:163
 in print_response at REPL.jl:134
 in print_response at REPL.jl:121
 in anonymous at REPL.jl:624
 in run_interface at /Applications/Julia-0.4.6.app/Contents/Resources/julia/lib/julia/sys.dylib
 in run_frontend at /Applications/Julia-0.4.6.app/Contents/Resources/julia/lib/julia/sys.dylib
 in run_repl at /Applications/Julia-0.4.6.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.4.6.app/Contents/Resources/julia/lib/julia/sys.dylib
```

**Comment by TotalVerb** [comment]
Thanks for trying it. I suspect your `Compat` version is `< v"0.8.2"`, which is the minimal version needed for the `show` overloading to be rewritten correctly on v0.4. Note that I bumped the REQUIRE in the package, but it does not take effect until tagged in METADATA. Try updating your packages.

But you're right that we should define `size`, especially since the current version extends `Base.AbstractVector`.

**Comment by TotalVerb** [comment]
I have pushed two additional commits:

 - Fourth commit defines `Base.size`, to better implement the `AbstractArray` interface
 - Fifth commit slightly improves the presentation of both single-line and multi-line (interactive) display

File: src/result.jl [hunk 1]
```diff
@@ -19,6 +19,7 @@ Base.show(io::IO, res::LintResult) = show(io, res.messages)
 end
 
 Base.length(r::LintResult) = length(r.messages)
+Base.size(r::LintResult) = size(r.messages)
```
Comment (Michael-Klassen) [inline src/result.jl]: Can you add tests when you add code. Even if it is just a simple sanity check.

File: src/result.jl [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+end
+
+function Base.show(io::IO, res::LintResult)
+    print(io, "LintResult(")
+    show(io, res.messages)
+    print(io, ")")
+end
+@compat function Base.show(io::IO, ::MIME"text/plain", res::LintResult)
+    if isempty(res)
+        Base.print_with_color(LINT_RESULT_COLORS[:OK], io, "No issues found.")
```
Comment (Michael-Klassen) [inline src/result.jl]: After playing with it a bit. I think it looks better when success returns nothing.

**Comment by Michael-Klassen** [comment]
Overall I like the new `LintResult`, much better then the old `returnMsgs` keyword solution.

File: src/result.jl (hunk 1 above)
Comment (TotalVerb) [inline src/result.jl]: Now testing this in lintself.

File: src/result.jl (hunk 2 above)
Comment (TotalVerb) [inline src/result.jl]: I'm OK with either. Reverted back to nothing.

**Comment by TotalVerb** [comment]
Thanks for the further review. I addressed the comments and squashed the latest `LintResult` commits into a single commit.
