### PR TITLE
Fix #252 ~ Update code to julia 1.0

### LINKED ISSUE #252: Tests fail on Julia 0.7
Lint.jl needs some updating:
```
(v0.7) pkg> add Lint#master
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Updating git-repo `https://github.com/tonyhffong/Lint.jl.git`
 Resolving package versions...
  Updating `~/.julia/environments/v0.7/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v0.7/Manifest.toml`
 [no changes]

(v0.7) pkg> test Lint
   Testing Lint
    Status `/tmp/tmpwkhh4L/Manifest.toml`
  [15f4f7f2] AutoHashEquals v0.2.0
  [34da2185] Compat v1.0.1
  [682c06a0] JSON v0.19.0
  [d4b2101a] Lint v0.5.2+ #master (https://github.com/tonyhffong/Lint.jl.git)
  [2a0f44e3] Base64  [`~/00Software/julia-0.7.0/bin/../share/julia/stdlib/v0.7/Base64`]
  [ade2ca70] Dates  [`~/00Software/julia-0.7.0/bin/../share/julia/stdlib/v0.7/Dates`]
  [8bb1440f] DelimitedFiles  [`~/00Software/julia-0.7.0/bin/../share/julia/stdlib/v0.7/DelimitedFiles`]
  [8ba89e20] Distributed  [`~/00Software/julia-0.7.0/bin/../share/julia/stdlib/v0.7/Distributed`]
  [b77e0a4c] InteractiveUtils  [`~/00Software/julia-0.7.0/bin/../share/julia/stdlib/v0.7/InteractiveUtils`]
  [76f85450] LibGit2  [`~/00Software/julia-0.7.0/bin/../share/julia/stdlib/v0.7/LibGit2`]
  [8f399da3] Libdl  [`~/00Software/julia-0.7.0/bin/../share/julia/stdlib/v0.7/Libdl`]
  [37e2e46d] LinearAlgebra  [`~/00Software/julia-0.7.0/bin/../share/julia/stdlib/v0.7/LinearAlgebra`]
  [56ddb016] Logging  [`~/00Software/julia-0.7.0/bin/../share/julia/stdlib/v0.7/Logging`]
  [d6f4376e] Markdown  [`~/00Software/julia-0.7.0/bin/../share/julia/stdlib/v0.7/Markdown`]
  [a63ad114] Mmap  [`~/00Software/julia-0.7.0/bin/../share/julia/stdlib/v0.7/Mmap`]
  [44cfe95a] Pkg  [`~/00Software/julia-0.7.0/bin/../share/julia/stdlib/v0.7/Pkg`]
  [de0858da] Printf  [`~/00Software/julia-0.7.0/bin/../share/julia/stdlib/v0.7/Printf`]
  [3fa0cd96] REPL  [`~/00Software/julia-0.7.0/bin/../share/julia/stdlib/v0.7/REPL`]
  [9a3f8284] Random  [`~/00Software/julia-0.7.0/bin/../share/julia/stdlib/v0.7/Random`]
  [ea8e919c] SHA  [`~/00Software/julia-0.7.0/bin/../share/julia/stdlib/v0.7/SHA`]
  [9e88b42a] Serialization  [`~/00Software/julia-0.7.0/bin/../share/julia/stdlib/v0.7/Serialization`]
  [1a1011a3] SharedArrays  [`~/00Software/julia-0.7.0/bin/../share/julia/stdlib/v0.7/SharedArrays`]
  [6462fe0b] Sockets  [`~/00Software/julia-0.7.0/bin/../share/julia/stdlib/v0.7/Sockets`]
  [2f01184e] SparseArrays  [`~/00Software/julia-0.7.0/bin/../share/julia/stdlib/v0.7/SparseArrays`]
  [10745b16] Statistics  [`~/00Software/julia-0.7.0/bin/../share/julia/stdlib/v0.7/Statistics`]
  [8dfed614] Test  [`~/00Software/julia-0.7.0/bin/../share/julia/stdlib/v0.7/Test`]
  [cf7118a7] UUIDs  [`~/00Software/julia-0.7.0/bin/../share/julia/stdlib/v0.7/UUIDs`]
  [4ec0a83e] Unicode  [`~/00Software/julia-0.7.0/bin/../share/julia/stdlib/v0.7/Unicode`]
┌ Warning: Deprecated syntax `try without catch or finally` at /home/ufechner/.julia/packages/Lint/7lMno/test/runtests.jl:58.
└ @ ~/.julia/packages/Lint/7lMno/test/runtests.jl:58
┌ Warning: Deprecated syntax `try without catch or finally` at /home/ufechner/.julia/packages/Lint/7lMno/test/runtests.jl:65.
└ @ ~/.julia/packages/Lint/7lMno/test/runtests.jl:65
┌ Warning: Deprecated syntax `try without catch or finally` at /home/ufechner/.julia/packages/Lint/7lMno/test/runtests.jl:73.
└ @ ~/.julia/packages/Lint/7lMno/test/runtests.jl:73
┌ Warning: `using A: B` will only be allowed for single bindings, not modules. Use `using A.B` instead
│   caller = ip:0x0
└ @ Core :-1
WARNING: importing deprecated binding Base.Nullable into LintCompat.
ERROR: LoadError: LoadError: ArgumentError: invalid type for argument x in method definition for BROADCAST at /home/ufechner/.julia/packages/Lint/7lMno/src/compat.jl:7
Stacktrace:
 [1] top-level scope at none:0
 [2] include at ./boot.jl:317 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1038
 [4] include at ./sysimg.jl:29 [inlined]
 [5] include(::String) at /home/ufechner/.julia/packages/Lint/7lMno/src/Lint.jl:3
 [6] top-level scope at none:0
 [7] include at ./boot.jl:317 [inlined]
 [8] include_relative(::Module, ::String) at ./loading.jl:1038
 [9] include(::Module, ::String) at ./sysimg.jl:29
 [10] top-level scope at none:2
 [11] eval at ./boot.jl:319 [inlined]
 [12] eval(::Expr) at ./client.jl:399
 [13] top-level scope at ./none:3
in expression starting at /home/ufechner/.julia/packages/Lint/7lMno/src/compat.jl:6
in expression starting at /home/ufechner/.julia/packages/Lint/7lMno/src/Lint.jl:29
ERROR: LoadError: Failed to precompile Lint [d4b2101a-7710-563d-8e49-77b01dd33fad] to /home/ufechner/.julia/compiled/v0.7/Lint/2G6O3.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1185
 [4] _require(::Base.PkgId) at ./logging.jl:311
 [5] require(::Base.PkgId) at ./loading.jl:852
 [6] macro expansion at ./logging.jl:311 [inlined]
 [7] require(::Module, ::Symbol) at ./loading.jl:834
 [8] include at ./boot.jl:317 [inlined]
 [9] include_relative(::Module, ::String) at ./loading.jl:1038
 [10] include(::Module, ::String) at ./sysimg.jl:29
 [11] include(::String) at ./client.jl:398
 [12] top-level scope at none:0
in expression starting at /home/ufechner/.julia/packages/Lint/7lMno/test/runtests.jl:1
ERROR: Package Lint errored during testing
```

### PR DESCRIPTION
**Pull request by FelipeLema**
Have a few fixes so far, but still incomplete. I made this PR for visibility so anyone can contribute 

Will ping when this is done (unit tests pass).

### CODE REVIEW

**Comment by FelipeLema** [comment]
Need help with `REQUIRES` → `Project.toml`. I have no idea what to do and the packages I've looked into (namely Dataframes.jl) have no info of such a migration.

**Comment by TotalVerb** [comment]
Thanks for this effort! I'll take some time to review this weekend or early next week. REQUIRES to Project.toml change  is not mandatory. I think we can leave it for a future PR.

**Comment by FelipeLema** [comment]
Oh, BTW I'm removing code for supporting anything previous to to v1.0

**Comment by TotalVerb** [comment]
We'll need to update the `.travis.yml` file also. Try something like: https://github.com/JuliaCI/TravisTest.jl/blob/master/.travis.yml except without the versions that won't be supported.

**Comment by TotalVerb** [comment]
Easy-to-read is important :+1:.

**Comment by TotalVerb** [comment]
By the way, `--compile-cache=no` is now `--compiled-modules=no`. See https://github.com/TotalVerb/EnglishText.jl/blob/master/.travis.yml for an example.

**Comment by FelipeLema** [comment]
Is there a particular reason why you're testing against the message when linting? Isn't the code enough?

**Comment by FelipeLema** [comment]
On another matter, I've bumped into this `:(#= none:1 =#)` again and I don't what its purpose, what we should do with it or even where to get more information about it.

**Comment by TotalVerb** [comment]
It's a `LineNumberNode`. The Julia parser produces these to keep track of line numbers, which are needed for reporting things like line numbers for errors. I'm not sure if Lint uses this information right now.

**Comment by TotalVerb** [comment]
As for testing against the message, it's probably enough to test against the error code. Historically we did not have error codes, and so we tested only against the message.

**Comment by FelipeLema** [comment]
was `LineNumberNode` introduced in v0.7 or later? just so I keep an eye out

**Comment by TotalVerb** [comment]
I think it was already around by 0.6, but I'm not sure.

**Comment by TotalVerb** [comment]
We will probably need to add `Test` to `REQUIRE`.

**Comment by FelipeLema** [comment]
I would say the other way around: remove `Test` from `REQUIRE`.

Isn't `Test` part of Julia's std lib? As so, should it be listed in `REQUIRE`?

**Comment by TotalVerb** [comment]
You are probably right. I'm not sure how to interpret this test failure then.

**Comment by FelipeLema** [comment]
nevermind. Using `+` the test case passes

**Comment by FelipeLema** [comment]
I don't think we should have W443 anymore. Docile.jl has been deprecated

**Comment by TotalVerb** [comment]
I don't think W443 has anything to do with Docile. The aim is to catch code like

```julia
@doc "this is a test"
f() = 0
```

which does not document function `f`. Perhaps what was intended was

**Comment by FelipeLema** [comment]
There's a `@test_broken` in test/curly.jl. Is this supposed to be "fixed sometime, currently WIP"? `Test` complains it passes

**Comment by TotalVerb** [comment]
I think it's a test that's supposed to pass but wasn't because of a bug, so it can be turned back into `@test` now.

File: src/statictype.jl [hunk 1]
```diff
@@ -114,30 +114,30 @@ operation on numbers is consistent with iteration order.
...
-else
-    include_string("""
-    length(::Type{T}) where T <: NTuple{N, Any} where N = Nullable{Int}(N)
-    """)
-end
+length(::Type{Union{}}) = 0
+length(::Type) = nothing
+length(::Type{T}) where {T <: Pair} = 2
+
+# if VERSION < v"0.6.0-dev.2123" # where syntax introduced by julia PR #18457
```
Comment (TotalVerb) [inline src/statictype.jl]: We can just drop these comments.

File: src/types.jl [hunk 2]
```diff
@@ -14,7 +14,7 @@ function linttype(ex::Expr, ctx::LintContext)
             adt = sube.args[i]
             if isa(adt, Symbol)
                 foundobj = lookup(ctx, adt)
-                if !isnull(foundobj) && get(foundobj).typeactual <: Type
+                if foundobj ≠ nothing && foundobj.typeactual <: Type
```
Comment (TotalVerb) [inline src/types.jl]: I'd recommend `!==` for `nothing` because it avoids possible problems with weird `foundobj`, which might overload `==` in a strange way. Not a big deal though.

**Comment by FelipeLema** [comment]
As you can see in the `test/variables.jl` file I just uploaded, there is a crucial part of the package working incorrectly. There is still some other bits that we can get along without (the `@doc` stuff), but without solving this test, there will be false positives all over the place.

**Comment by FelipeLema** [comment]
Now string -> expression code is more organized. At least now it's got its own unit tests.

Go ahead with the merge if you're OK with it.

File: src/Lint.jl [hunk 3]
```diff
@@ -25,9 +26,6 @@ const SIMILARITY_THRESHOLD = 10.0
 macro lintpragma(s)
 end
 
-# needed for BROADCAST
-include("compat.jl")
```
Comment (TotalVerb) [inline src/Lint.jl]: We can delete the compat.jl file now, right?

Comment (FelipeLema) [reply src/Lint.jl]: yup

**Comment by TotalVerb** [comment]
Thanks! The next problem is how to release this package, since attobot is not installed. We may need to make a METADATA PR manually, but I have not done that in so long.
