### PR TITLE
Simplify code thanks to migration from v0.4

### LINKED ISSUE #56: Subtypes of immutable types -- linting their field assignments
Complex and AbstractArray are abstract immutable types.

However, Complex{Float64} is an concrete immutable type, but many subtypes of AbstractArray are mutable. There's no way for lint to tell if a generic function defined on the abstract type is trying to mutate an immutable subtype, or not.

While trying to catch setting complex field, there are now lots of false positives in linting functions on AbstractArrays.

### LINKED ISSUE #79: Incorrect type assumption with int()
```
function lmatrix(g::Graph)
    n_v = nv(g)
    A = int(adjacency_matrix(g))   # note that this creates a sparse matrix of integers
    D = spdiagm(sum(A,2)[:])
    return D - A
end
```

yields

```
ERROR  sum: ErrorException("no method found for the specified argument types")
                                         Signature: (Int64,Int64)
```

Also curiously, it doesn't warn that I'm not using `n_v`.

### LINKED ISSUE #81: Adapt to the new [ a, b ] non-concat behavior
https://github.com/JuliaLang/julia/pull/8599

### LINKED ISSUE #84: Spurious "ERROR  g is of an immutable type LightGraphs.AbstractGraph"
```
abstract AbstractGraph
...

function add_vertex!(g::AbstractGraph)
    n = length(vertices(g)) + 1
    g.vertices = 1:n
    return n
end
```

### LINKED ISSUE #88: Parametric method using parametric type of Complex
I believe there is an issue for parametric method using parametric type of Complex.

$ cat temp.jl
F = Float64
Complex{F}

type MyType{T}
    a::T
end

function f{A}(z::Complex{A})
end

function g{B}(z::MyType{B})
end

julia> using Lint

julia> lintfile("temp.jl")
temp.jl:8 [f              ] ERROR  Lint fails to parse Complex{A}
                                   TypeError(:Complex,"T",T<:Real,Any)
temp.jl:8 [f              ] INFO   Argument declared but not used: z
temp.jl:11 [g              ] INFO   Argument declared but not used: z

julia> include("temp.jl")
g (generic function with 1 method)

### LINKED ISSUE #122: Type assertion and default seem inconsistent
I believe the linter may not be interpreting parametric functions correctly:

``` julia
julia> using Lint

julia> lintstr("foo{S<:AbstractString}(args::Array{S}=ARGS) = typeof(args)")
1-element Array{Lint.LintMessage,1}:
 none:1 [foo            ] ERROR  args type assertion and default seem inconsistent
```

ARGS is of the type `Array{UTF8String,1}` which definitely matches the type assertion.

### LINKED ISSUE #135: ErrorException when symbols are imported
Example:

``` julia
julia> import Base: ==, hash, length, size, -, +, ./, norm, dot, angle, cross, vec, any, print, show, parse

julia> lintstr("import Base: ==, hash, length, size, -, +, ./, norm, dot, angle, cross, vec, any, print, show, parse")
ErrorException("syntax: incomplete: premature end of input")
import Base.==
ErrorException("syntax: incomplete: premature end of input")
import Base.-
ErrorException("syntax: incomplete: premature end of input")
import Base.+
ParseError("invalid operator \"../\"")
import Base../
0-element Array{Lint.LintMessage,1} 

```

### LINKED ISSUE #167: ERROR: type String has no field head
```julia
julia> using Lint

julia> lintstr("""type love
       who
       "Julia :)"
       love() = "yes"
       end
       """)
ERROR: type String has no field head
 in linttype(::Expr, ::Lint.LintContext) at C:\Users\lizhi\.julia\v0.5\Lint\src\types.jl:99
 in lintexpr(::Expr, ::Lint.LintContext) at C:\Users\lizhi\.julia\v0.5\Lint\src\Lint.jl:228
 in lintstr(::String, ::Lint.LintContext, ::Int64) at C:\Users\lizhi\.julia\v0.5\Lint\src\Lint.jl:151
 in lintstr(::String) at C:\Users\lizhi\.julia\v0.5\Lint\src\Lint.jl:124
```

This error happens if you want to add some inline doc to the inner constructor. One way to bypass this error:
at https://github.com/tonyhffong/Lint.jl/blob/master/src/types.jl#L99,
before the first use of ``def.head``, add the following code
```julia
elseif !(:head in fieldnames(def))
    nothing
```

### LINKED ISSUE #195: E424 : nested vect is treated as a 1-dimensional array. Use [a;b] instead
```julia
julia> lintfile("filename.jl","[[1,1],[1,2]]")
filename.jl:1 E424 : nested vect is treated as a 1-dimensional array. Use [a;b] instead


julia> lintfile("filename.jl","Array[[1,1],[1,2]]")


julia> 
```

### PR DESCRIPTION
**Pull request by TotalVerb**
The first commit deletes a lot of code to guess the return types of function calls in cases where inference can handle it.

The second commit replaces `evaltype` and `parsetype` with a single function that is more general and sophisticated than the existing one.

The third commit deletes a large amount of 0.4-specific code that is no longer necessary, and deletes some uses of `eval` where safer, less dynamic infrastructure exists.

The fourth commit fixes bug #167 and also replaces some uses of `typeof(x) == T` with `isa(x, T)`.

The fifth commit includes tests for all the bugs fixed by this PR, except #167 which is tested in test/docs.jl.

The sixth commit improves the detection of when a type is considered mutable, which fixes several old issues; both #56 and #84 are fixed.

The seventh commit removes code specific to 0.4 dealing with vect, which is now well-defined and legal. This fixes #81 and #195.

The eighth and ninth commits fix `Dict` linting on v0.6, which was broken due to a change in the `Expr` representation.

The tenth commit disables some tests on 0.5 for which the special cases allowing them to pass have been removed. In 0.6 and future releases those special cases are not necessary, and so I feel it is unnecessary to keep special cases around for those obscure cases.

The eleventh commit disables the self-lint test because of #200, and fixes a test hang on 0.6.

All of these issues are fixed, and test has been added to test/bugs.jl:

Fixes #56 
Fixes #79
Fixes #81 
Fixes #84
Fixes #88
Fixes #122 
Fixes #167 [test is in test/doc.jl]
Fixes #195

I checked several old issues to see if they were fixed, and these ones were, but probably not by this PR (likely some intervening change fixed them). Tests have been added (see test/bugs.jl) to confirm that the bugs are fixed. I include them here because this PR tests for them, and because GitHub should close them when this is merged.

Closes #135

### CODE REVIEW

**Comment by TotalVerb** [comment]
There seems to be a hang in the v0.6 tests. I'll investigate that.

**Comment by TotalVerb** [comment]
@tonyhffong @Michael-Klassen @TeroFrondelius This is ready for review/merge.

File: test/server.jl [hunk 1]
```diff
@@ -36,24 +36,24 @@ end
     socket = connect(port)
     lintbyserver(socket)
     response = ""
-    line = ""
-    while line != "\n"
+    line = "."
+    while !isempty(line)
```
Comment (TeroFrondelius) [inline test/server.jl]: My guess is that this change hangs the lintserver().

Comment (TotalVerb) [inline test/server.jl]: This change was needed to prevent a hang. On v0.6, `readline` changed to remove trailing newlines.

Comment (TeroFrondelius) [inline test/server.jl]: My bad, I was late with my review, I thought the lintserver hang was still a problem.

**Comment by TeroFrondelius** [comment]
For me this looks good. Although my competence is not enough to review all the changes and their possible effects. Then again code test coverage is relatively high, if tests pass then I want to believe this is not breaking anything.
